### ISSUE TITLE
SpanDecorator NPE - Some time the remote address can be null

### ISSUE THREAD

**Issue by gpolaert** [opentracing-contrib/java-elasticsearch-client#1]
I'm testing the integration via Unit Tests.
I had a NPE because the remote address was null.

https://github.com/opentracing-contrib/java-elasticsearch-client/blob/master/src/main/java/io/opentracing/contrib/elasticsearch/SpanDecorator.java#L28

I think the Integration has to be more protective and not returning any errors.
Should we handle this case with a default value or something like that?

**Comment by malafeev** [comment]
My fault. I will add null check.

**Comment by gpolaert** [comment]
``
