### ISSUE TITLE
span reports 401 http status on success

### ISSUE THREAD

**Issue by randallt** [opentracing-contrib/java-elasticsearch-client#18]
I am using the TracingHttpClientConfigCallback to add spans to my elastic search REST client use. However, we also use credentials, as mentioned in 

https://stackoverflow.com/questions/48185570/add-authentication-in-elasticsearch-high-level-client-for-java

so I pass the credentials callback in as a parameter to the TracingHttpClientConfigCallback. When I didn't do that, my queries failed with a 401. Now my queries succeed, but the elasticsearch client spans still show a status of 401, even though I can confirm in the logs that the query was successful. 

I'm wondering if the authentication mechanism is somehow causing an initial 401. 

Has anyone seen this, or have recommendations on how to address it?

A secondary issue is that the time reported in the span seems very short compared to my logging and other spans. This could be linked to the 401 problem, however.

We are using version 6.6.1 of the Elasticsearch client API JARs.

**Comment by malafeev** [comment]
@randallt I tried to reproduce your issue
```
final CredentialsProvider credentialsProvider = new BasicCredentialsProvider();
    credentialsProvider.setCredentials(AuthScope.ANY,
        new UsernamePasswordCredentials("elastic", "MagicWord"));

final HttpClientConfigCallback callback = new HttpClientConfigCallback() {

      @Override
      public HttpAsyncClientBuilder customizeHttpClient(
          HttpAsyncClientBuilder httpAsyncClientBuilder) {
        return httpAsyncClientBuilder.setDefaultCredentialsProvider(credentialsProvider);
      }
    };

RestClient restClient = RestClient.builder(
        new HttpHost("localhost", HTTP_PORT, "http"))
        .setHttpClientConfigCallback(new TracingHttpClientConfigCallback(tracer, callback))
        .build();

HttpEntity entity = new NStringEntity(
        "{\n" +
            "    \"user\" : \"kimchy\",\n" +
            "    \"post_date\" : \"2009-11-15T14:12:12\",\n" +
            "    \"message\" : \"trying out Elasticsearch\"\n" +
            "}", ContentType.APPLICATION_JSON);

Request request = new Request("PUT", "/twitter/tweet/1");
request.setEntity(entity);
Response indexResponse = restClient.performRequest(request);
```

works fine for me, I see http status 200 in spans.

**Comment by randallt** [comment]
Hmm, we also set an SSLContext and disable auth caching in this manner:

```
    private static @Nonnull RestClientBuilder.HttpClientConfigCallback createHttpClientCallback(@Nullable CredentialsProvider credentialsProvider, @Nullable SSLContext sslContext){
        return httpClientBuilder -> {
            if (sslContext != null) {
                httpClientBuilder.setSSLContext(sslContext);
            }
            if (credentialsProvider != null) {
                httpClientBuilder.disableAuthCaching();
                httpClientBuilder.setDefaultCredentialsProvider(credentialsProvider);
            }
            return httpClientBuilder;
        };
    }
```

Where the above is used like:

```
...
SSLContext sslContext = SSLContexts.custom().loadTrustMaterial(new URL(config.getTruststorePath()), config.getTruststorePassword().toCharArray(), new TrustSelfSignedStrategy()).build();
CredentialsProvider credentialsProvider = new BasicCredentialsProvider();
credentialsProvider.setCredentials(AuthScope.ANY, new UsernamePasswordCredentials(config.getUsername(), config.getPassword()));
restClient.setHttpClientConfigCallback(createHttpClientCallback(credentialsProvider, sslContext));
return new RestHighLevelClient(restClient);
```
Can you try with these modifications? Any other ideas why it might not be working for me?

**Comment by malafeev** [comment]
looks like `httpClientBuilder.disableAuthCaching();` is changing behavior

**Comment by randallt** [comment]
Are you looking into a fix, or should I investigate not using the TracingHttpClientConfigCallback at all?

**Comment by malafeev** [comment]
I'm trying to fix it...

**Comment by randallt** [comment]
I tried out the merged code, and it appears to work. Thanks for the quick turn around!
