### ISSUE TITLE
Support for Elasticsearch 5

### ISSUE THREAD

**Issue by emersonborges** [opentracing-contrib/java-elasticsearch-client#4]
It would be nice to have a separated module for Elasticsearch 5, the current version doesn't work for Elasticsearch 5.5.0 transport client... Maybe slipt in 3 modules, a core, elasticsearch5 and elasticsearch6.

**Comment by malafeev** [comment]
in that case I'm not sure that instrumentation  of 5.6.10 (latest 5) will be compatible with 5.5.0.
If
- elasticsearch5 will support only latest Elasticsearch 5 (5.6.10 as of now)
- elasticsearch6 will support only latest Elasticsearch 6 (6.3.1 as of now).

will be OK?

cc @tedsuo

**Comment by emersonborges** [comment]
Hi @malafeev, it will be ok to support the latest version of 5 and 6, I believe will be compatible.

**Comment by malafeev** [comment]
@emersonborges will do

**Comment by emersonborges** [comment]
thanks @malafeev!

**Comment by malafeev** [comment]
done in version **0.0.5**
